Index
Ashah15/Design-Teardown pull request #1
Opened 2019-07-25 22:50 UTC by Ashah15

2019-07-26 03:56 UTC, Ispirett requested changes
Hey, folks @Ashah15   @MarvellousUbani  great work with this project you are doing a fantastic job with this heat map 1st_place_medal . :100:   There are just a few changes that Mircoverse requires before this project can be completed.

##### Each `section` container should have articles tags instead of the divs
#### Also dont forget this section.

![smashing](https://user-images.githubusercontent.com/38801423/61924904-dac64600-af37-11e9-91fd-06573178aa3b.png)
 
**Must say I love this project so far the font looks beautiful and you folks positioned elements well.**

2019-07-26 03:56 UTC, Ispirett commented on index.html
> +<body>
Don't forget to put the `<main>` tag

2019-07-26 03:56 UTC, Ispirett commented on index.html
> +  <section class="first-section">
Each section should  have and article tag!

2019-07-26 03:56 UTC, Ispirett commented on index.html
> +          <ul class="footer__topics__list"><li class="footer__topics__item"><a href="/category/accessibility">Accessibility</a></li><li class="footer__topics__item"><a href="/category/android">Androi
User display: flex or display float for list the `<li>` tags

2019-07-26 03:56 UTC, Ispirett commented on index.html
> +      <ul>
Use display:flex or float to list the items here.

2019-07-27 01:14 UTC, bolah2009 commented
Currently under review

2019-07-27 01:34 UTC, bolah2009 approved these changes
## Nice Job [Asha](@Ashah15) and [Marvellous](@MarvellousUbani) :clap: :1st_place_medal: 

The [clone](https://raw.githack.com/Ashah15/Design-Teardown/index/index.html) looks good to me and shows the use of visual hierarchy and typography. :+1: 

#### Consider checking out the commets before merging.

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-07-27 01:34 UTC, bolah2009 commented on css/style.css
> +  flex:none !important;
`SUGGESTION`

Let's avoid the use `!important` in CSS properties as much as possible.

> Using !important, however, is **bad practice** and should be avoided because it makes debugging more difficult by breaking the natural cascading in your stylesheets.  

Learn more on why you shouldn't use it and also tips on how to you avoid it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#The_!important_exception)

2019-07-27 01:34 UTC, bolah2009 commented on css/style.css
> + flex:none !important;
Check [this comment]() on the use of `!important`.

2019-07-27 01:34 UTC, bolah2009 commented on css/style.css
> +  flex: none !important;
Check [this comment]() on the use of `!important`.

2019-07-27 01:34 UTC, bolah2009 commented on css/style.css
> +  font-size: 1.4rem !important;
Check [this comment]() on the use of `!important`.

2019-07-30 15:24 UTC, merged